### ISSUE TITLE
Rewrite all urls in a playlist

### ISSUE THREAD

**Issue by PilaScat** [marcelGoerentz/Threadfin#23]
I again, I need to use threadfin via vpn on another server in another lan, when I connect with the vpn ip to my server I get the m3u and xmltv, but when I stream it tries to connect at the other threadfin as it is in the same lan, I need a way to rewrite the ips in the second lan to match the vpn ip of the first lan, I tried to modify the urls manually to test but threadfin overwrites
Could you add a field to do this?

**Comment by marcelGoerentz** [comment]
You need to set the domain option I guess. That will overwrite the IPs within the m3u and xml file.

**Comment by PilaScat** [comment]
Yes it does, but only in egress, not in ingress

**Comment by marcelGoerentz** [comment]
Maybe you need a proxy?

**Comment by marcelGoerentz** [comment]
As far as I know there is a new option that I‘ve synced from the original project.

**Comment by marcelGoerentz** [comment]
Maybe that will help you

**Comment by PilaScat** [comment]
I tried to use it but it doesn't change, probably I don't know how to use it

**Comment by marcelGoerentz** [comment]
It should forward every stream to a specific endpoint. I‘ll have to check how it works, before I can say anything specific

**Comment by marcelGoerentz** [comment]
These are the comments to the code that has been checked into the original project:
https://github.com/Threadfin/Threadfin/pull/325

So this is something with the buffer.

To be honest I don‘t think that Threadfin should touch the urls in the original playlist as this could lead to malformed URL’s. Even the force https option is a bad option in Threadfin and I just left it since it has been used eventually by few users. Therefore I will not implement this feature. Sorry for the inconvenience.
